routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CountersController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\MetablogController;
use App\Http\Controllers\Admin\MetaController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\WorksController;
use App\Http\Controllers\Admin\YourProjectController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home']);

Route::post('/contact', [ContactController::class, 'store']);

Route::get('/route-cache', function() {
     \Artisan::call('route:clear');
     return 'Routes cache cleared';
 });

 //Clear config cache
 Route::get('/config-cache', function() {
     \Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 
  //Clear config cache
 Route::get('/config-clear', function() {
     \Artisan::call('config:clear');
     return 'Config cache cleared';
 });

 // Clear application cache
 Route::get('/clear-cache', function() {
     \Artisan::call('cache:clear');
     return 'Application cache cleared';
 });


//Route::get('lang/{lang}', [HomeController::class, 'switchLang'])->name('lang.switch');
//Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'HomeController@switchLang']);
Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {
    Route::get('/login_view', [AuthController::class, 'loginView'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', [AuthController::class, 'home']);
        Route::get('/editAbout', [SettingController::class, 'editAbout']);
        Route::post('/updateAbout', [SettingController::class, 'updateAbout']);
        Route::get('/editWe', [SettingController::class, 'editWe']);
        Route::post('/updateWe', [SettingController::class, 'updateWe']);
        Route::resource('yourProject', YourProjectController::class);
        Route::resource('services', ServicesController::class);
        Route::resource('contact', ContactController::class);
        Route::get('/delContact/{id}', [ContactController::class, 'destroy']);
        Route::get('/delService/{id}', [ServicesController::class, 'destroy']);
        Route::resource('works', WorksController::class);
        Route::get('/delWork/{id}', [WorksController::class, 'destroy']);
        Route::resource('counters', CountersController::class);
        Route::resource('media', MediaController::class);
        Route::resource('blogs', BlogController::class);
        Route::get('/delBlog/{id}', [BlogController::class, 'destroy']);
      
        Route::resource('meta', MetaController::class);
        Route::resource('bolg_meta', MetablogController::class);



        


        Route::get('/logout', [AuthController::class, 'logout']);

    });
});




Route::group(['middleware'=>['localizationRedirect', 'localeViewPath' ,'localeCookieRedirect','localeSessionRedirect']
,'prefix' => LaravelLocalization::setLocale()],function ()
{
    Route::group(['middleware'=>'language'],function ()
    {
        Route::get('/', [HomeController::class, 'index']);
        Route::resource('home_blogs', \App\Http\Controllers\BlogController::class);
    });
});

app/Models/Blog.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model implements TranslatableContract
{
    use HasFactory, Translatable;

    protected $fillable = ['image'];

    public $translatedAttributes = ['title','content'];

}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class BlogController extends Controller
{
    public function index(){
        $blogs=Blog::orderBy('created_at','desc')->get();
        return view ('admin.blogs.index',['blogs'=>$blogs]);
    }

    public function create(){
        return view('admin.blogs.create');
    }
    public function store(Request $request){
        if($request->file != ''){
            $path = 'images/blogs/';


            $file = $request->file;
            $filename = $file->getClientOriginalName();
            $filename = $path.$filename;
            $file->move($path, $filename);


        }
        $blog=Blog::create([
            'image'      =>$filename,
            'ar'=>['title'=>$request->title_ar
                ,'content' => $request->content_ar
            ],
            'en'=>['title'=>$request->title_en
                ,'content' => $request->content_en
            ]
        ]);


        return redirect(route('admin_panel.blogs.index'))->with(['message'=>'تمت الإضافة بنجاح']);
    }
    public function edit(Request $request,$id){
        $blog=Blog::find($id);
        return view('admin.blogs.edit',['blogs'=>$blog]);
    }

    public function update(Request $request,$id){
        $blog=Blog::find($id);
        if($request->file != ''){
            (File::exists($blog->image)) ? File::delete($blog->image) : Null;
            $path = 'images/blogs/';

            $file = $request->file;
            $filename = $file->getClientOriginalName();
            $filename = $path.$filename;
            $file->move($path, $filename);

            $blog->update([
                'image'      =>$filename
            ]);
        }

        $blog->update([
            'ar'=>['title'=>$request->title_ar
                ,'content' => $request->content_ar
            ],
            'en'=>['title'=>$request->title_en
                ,'content' => $request->content_en
            ]
        ]);

        return redirect(route('admin_panel.blogs.index'))->with(['message'=>'تم التعديل بنجاح']);
    }
    public function destroy($id){
        $blog=Blog::find($id);
        (File::exists($blog->image)) ? File::delete($blog->image) : Null;
        $blog->delete();
        return redirect()->back()->with(['message'=>'تم الحذف بنجاح']);
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\Media;
use App\Models\Metablog;
use \Illuminate\Support\Str;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index(){

        $blogs=Blog::orderBy('created_at','desc')->paginate(6);
        $media=Media::first();
        $blog_meta=Metablog::first();
        
        return view ('blogs.index',['blogs'=>$blogs,'media'=>$media,'blog_meta'=>$blog_meta]);
    }
    public function show($id){
        $blog=Blog::find($id);
        $media=Media::first();
        $blog_meta=Metablog::first();
        $last_blogs=$blogs=Blog::orderBy('created_at','desc')->take(3)->get();
        return view('blogs.item',['blog'=>$blog,'media'=>$media,'last_blogs'=>$last_blogs, 'blog_meta'=>$blog_meta]);
    }
}

resources/views/admin/blogs/create.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item ">المدونة </li>
                                    <li class="breadcrumb-item active"> إضافة مدونة </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">إضافة مدونة </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.blogs.store')}}" enctype="multipart/form-data" >
                                    @method('POST')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label for="inputAddress" class="form-label"> الصورة </label>
                                            <input type="file" class="form-control"  placeholder="1234 Main St" name="file" required>
                                        </div>

                                        <div class="col-md-12">
                                            <label for="inputEmail4" class="form-label">العنوان باللغة العربية </label>
                                            <input type="text" class="form-control"  name="title_ar" required>
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputEmail4" class="form-label">المحتوى باللغة العربية </label>
                                            <textarea id="text-ar"  name="content_ar" required></textarea>
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputEmail4" class="form-label">العنوان باللغة الأجنبية </label>
                                            <input type="text" class="form-control"  name="title_en" required>
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputEmail4" class="form-label">المحتوى باللغة الأجنبية </label>
                                            <textarea id="text-en"   name="content_en" required></textarea>
                                        </div>

                                        <div class="col-12">
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-primary">إضافة </button>
                                            </div>
                                        </div>

                                    </div>

                                </form>
                                <script>
                                    $(document).ready(function() {
                                        $('#text-en').summernote();
                                    });
                                    $(document).ready(function() {
                                        $('#text-ar').summernote();
                                    });

                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/blogs/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item ">المدونة </li>
                                    <li class="breadcrumb-item active"> تعديل مدونة </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">تعديل مدونة </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">

                                <form class=" g-3" method="post" action="{{route('admin_panel.blogs.update',$blogs->id)}}" enctype="multipart/form-data" >
                                    @method('PATCH')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="col-md-12">
                                        <label for="inputAddress" class="form-label"> الصورة </label>
                                        <input type="file" class="form-control"  placeholder="1234 Main St" name="file" >
                                    </div>

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">العنوان باللغة العربية </label>
                                        <input type="text" class="form-control" value="{{$blogs->translate('ar')->title}}" name="title_ar">
                                    </div>
                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">المحتوى باللغة العربية </label>
                                        <textarea id="text-ar" class="form-control" name="content_ar">{{$blogs->translate('ar')->content}}</textarea>
                                    </div>
                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">العنوان باللغة الأجنبية </label>
                                        <input type="text" class="form-control" value="{{$blogs->translate('en')->title}}" name="title_en">
                                    </div>
                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">المحتوى باللغة الأجنبية </label>
                                        <textarea id="text-en" class="form-control" name="content_en">{{$blogs->translate('en')->content}}</textarea>
                                    </div>

                                    <div class="col-12">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">تعديل</button>
                                        </div>
                                    </div>


                                </form>
                                <script>
                                    $(document).ready(function() {
                                        $('#text-en').summernote();
                                    });
                                    $(document).ready(function() {
                                        $('#text-ar').summernote();
                                    });

                                </script>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/blogs/index.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active">المدونة </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->

        <!-- Content -->
        <div class="col-12" style="margin:2% 2% auto;">
            <div class="user-profile ">
                <div class="widget-content widget-content-area">
                    {{--                        <div class=" " style="padding:2% 2% 0px; " >--}}
                    {{--                            <h3 class="">تعديل المحتوى </h3>--}}
                    {{--                        </div>--}}

                    <div class="" style="padding: 2%;">
                        <div class="container">
                            @if(session()->has('message'))

                                <div class="alert alert-success">

                                    {{ session()->get('message') }}

                                </div>

                            @endif
                             <div class="table-responsive" id="t1">
                                <a class="btn btn-primary mb-2 me-4" href="{{route('admin_panel.blogs.create')}}">إضافة مدونة </a>

                                <table id="myTable1" class="table table-striped table-bordered table-sm">
                                    <thead>
                                    <tr>
                                        <th class="text-center" scope="col"></th>
                                        <th scope="col">الصورة </th>
                                        <th scope="col">العنوان باللغة العربية </th>
                                        <th scope="col">المحتوى باللغة العربية </th>
                                        <th scope="col">العنوان باللغة الأجنبية </th>
                                        <th scope="col">المحتوى باللغة الأجنبية </th>
                                        <th scope="col">التاريخ </th>

                                        <th class="text-center" scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <?php $counter=1;?>
                                    @foreach($blogs as $blog)

                                        <tr>
                                            <td>
                                                <p class="text-center">{{$counter}}</p>
                                                <span class="text-success"></span>
                                                <?php $counter++;?>
                                            </td>
                                            <td>
                                                <div class="media">
                                                    <div class="avatar me-2">
                                                        <img alt="avatar" src="/{{$blog->image}}" class="rounded-circle" />
                                                    </div>

                                                </div>
                                            </td>
                                            <td>
                                                <p class="mb-0">{{$blog->translate('ar')->title}}</p>
                                                <span class="text-success"></span>
                                            </td>
                                           <td>
                                                <p class="mb-0">{!!$blog->translate('ar')->content!!}</p>
                                                <span class="text-success"></span>
                                            </td>

                                            <td>
                                                <p class="mb-0">{{$blog->translate('en')->title}}</p>
                                                <span class="text-success"></span>
                                            </td>
                                            <td>
                                                <p class="mb-0">{!!$blog->translate('en')->content!!}</p>
                                                <span class="text-success"></span>
                                            </td>
                                            <td>
                                                <p class="mb-0">{{$blog->created_at->toDateString()}}</p>
                                                <span class="text-success"></span>
                                            </td>

                                            <td class="text-center" width="10%">
                                                <div class="action-btns">
                                                    <a href="{{route('admin_panel.blogs.edit',$blog->id)}}" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="تعديل">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                                    </a>
                                                    <a href="/admin_panel/delBlog/{{$blog->id}}" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="حذف">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                    </a>

                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->




@endsection