routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CountersController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\MetablogController;
use App\Http\Controllers\Admin\MetaController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\WorksController;
use App\Http\Controllers\Admin\YourProjectController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home']);

Route::post('/contact', [ContactController::class, 'store']);

Route::get('/route-cache', function() {
     \Artisan::call('route:clear');
     return 'Routes cache cleared';
 });

 //Clear config cache
 Route::get('/config-cache', function() {
     \Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 
  //Clear config cache
 Route::get('/config-clear', function() {
     \Artisan::call('config:clear');
     return 'Config cache cleared';
 });

 // Clear application cache
 Route::get('/clear-cache', function() {
     \Artisan::call('cache:clear');
     return 'Application cache cleared';
 });


//Route::get('lang/{lang}', [HomeController::class, 'switchLang'])->name('lang.switch');
//Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'HomeController@switchLang']);
Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {
    Route::get('/login_view', [AuthController::class, 'loginView'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', [AuthController::class, 'home']);
        Route::get('/editAbout', [SettingController::class, 'editAbout']);
        Route::post('/updateAbout', [SettingController::class, 'updateAbout']);
        Route::get('/editWe', [SettingController::class, 'editWe']);
        Route::post('/updateWe', [SettingController::class, 'updateWe']);
        Route::resource('yourProject', YourProjectController::class);
        Route::resource('services', ServicesController::class);
        Route::resource('contact', ContactController::class);
        Route::get('/delContact/{id}', [ContactController::class, 'destroy']);
        Route::get('/delService/{id}', [ServicesController::class, 'destroy']);
        Route::resource('works', WorksController::class);
        Route::get('/delWork/{id}', [WorksController::class, 'destroy']);
        Route::resource('counters', CountersController::class);
        Route::resource('media', MediaController::class);
        Route::resource('blogs', BlogController::class);
        Route::get('/delBlog/{id}', [BlogController::class, 'destroy']);
      
        Route::resource('meta', MetaController::class);
        Route::resource('bolg_meta', MetablogController::class);



        


        Route::get('/logout', [AuthController::class, 'logout']);

    });
});




Route::group(['middleware'=>['localizationRedirect', 'localeViewPath' ,'localeCookieRedirect','localeSessionRedirect']
,'prefix' => LaravelLocalization::setLocale()],function ()
{
    Route::group(['middleware'=>'language'],function ()
    {
        Route::get('/', [HomeController::class, 'index']);
        Route::resource('home_blogs', \App\Http\Controllers\BlogController::class);
    });
});

resources/views/admin/layouts/footer.blade.php
<!--  BEGIN FOOTER  -->
<div class="footer-wrapper">
    <div class="footer-section f-section-1">
    </div>
    <div class="footer-section f-section-2">
    </div>
</div>
<!--  END FOOTER  -->

resources/views/admin/layouts/navigation.blade.php
<!--  BEGIN NAVBAR  -->
<div class="header-container container-xxl">
    <header class="header navbar navbar-expand-sm expand-header">

        <ul class="navbar-item theme-brand flex-row  text-center">
            <li class="nav-item theme-logo">
                <a href="admin.index">
                    <img src="{{ asset('assets/img/favicon.png') }}" alt="logo">
                </a>
            </li>
            <li class="nav-item theme-text">
                <a href="assets/img/favicon.png" class="nav-link"> Engineer Faisal </a>
            </li>
        </ul>


        <ul class="navbar-item flex-row ms-lg-auto ms-0 action-area">
<!--
            <li class="nav-item dropdown language-dropdown">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle" id="language-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="{{ asset('src/assets/img/1x1/us..svg') }}" class="flag-width" alt="flag">
                </a>
                <div class="dropdown-menu position-absolute" aria-labelledby="language-dropdown">
                    <a class="dropdown-item d-flex" href="javascript:void(0);"><img src="{{ asset('src/assets/img/1x1/us..svg') }}" class="flag-width" alt="flag"> <span class="align-self-center">&nbsp;English</span></a>
                    <a class="dropdown-item d-flex" href="javascript:void(0);"><img src="{{ asset('src/assets/img/1x1/tr..svg') }}" class="flag-width" alt="flag"> <span class="align-self-center">&nbsp;Turkish</span></a>
                    <a class="dropdown-item d-flex" href="javascript:void(0);"><img src="{{ asset('src/assets/img/1x1/br..svg') }}" class="flag-width" alt="flag"> <span class="align-self-center">&nbsp;Portuguese</span></a>
                    <a class="dropdown-item d-flex" href="javascript:void(0);"><img src="{{ asset('src/assets/img/1x1/in..svg') }}" class="flag-width" alt="flag"> <span class="align-self-center">&nbsp;Hindi</span></a>
                    <a class="dropdown-item d-flex" href="javascript:void(0);"><img src="{{ asset('src/assets/img/1x1/de..svg') }}" class="flag-width" alt="flag"> <span class="align-self-center">&nbsp;German</span></a>
                </div>
            </li>
-->
            <li class="nav-item theme-toggle-item">
                <a href="javascript:void(0);" class="nav-link theme-toggle">
                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-moon dark-mode"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>
                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sun light-mode"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>
                </a>
            </li>


            <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar-container">
                        <div class="avatar avatar-sm avatar-indicators avatar-online">
                            <img alt="avatar" src="{{asset('images/avatar.png')}}" width="80" height="80" class="rounded-circle">
                        </div>
                    </div>
                </a>

                <div class="dropdown-menu position-absolute" aria-labelledby="userProfileDropdown">
                    <div class="user-profile-section">
                        <div class="media mx-auto">
                            <div class="emoji me-2">
                                &#x1F44B;
                            </div>
                            <div class="media-body">
                                <h5>{{$admin->name}}</h5>
                                <p>{{$admin->email}}</p>
                            </div>
                        </div>
                    </div>
{{--                    <div class="dropdown-item">--}}
{{--                        <a href="{{route('admin_panel.profile.index')}}">--}}
{{--                            <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg> <span> الملف الشخصي </span>--}}
{{--                        </a>--}}
{{--                    </div>--}}
{{--                    <div class="dropdown-item">--}}
{{--                        <a href="/admin_panel/edit_password">--}}
{{--                            <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg> <span> تغيير كلمة المرور </span>--}}
{{--                        </a>--}}
{{--                    </div>--}}
                    <div class="dropdown-item">
                        <a href="/admin_panel/logout">
                            <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg> <span>تسجيل الخروج</span>
                        </a>
                    </div>
                </div>

            </li>
        </ul>
    </header>
</div>
<!--  END NAVBAR  -->

resources/views/admin/layouts/scripts.blade.php
<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('js/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('js/mousetrap.min.js') }}"></script>
<script src="{{ asset('js/waves.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<!-- END GLOBAL MANDATORY SCRIPTS -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<script src="{{ asset('js/apexcharts.min.js') }}"></script>
<script src="{{ asset('js/dash_1.js') }}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->

resources/views/admin/layouts/sidebar.blade.php
<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="sidebar">

{{--        <div class="navbar-nav theme-brand flex-row  text-center">--}}
{{--            <div class="nav-logo">--}}
{{--                <div class="nav-item theme-logo">--}}
{{--                    <a href="./index.html">--}}
{{--                        <img src="{{ asset('src/assets/img/logo..svg') }}" class="navbar-logo" alt="logo">--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--                <div class="nav-item theme-text">--}}
{{--                    <a href="./index.html" class="nav-link"> CORK </a>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="nav-item sidebar-toggle">--}}
{{--                <div class="btn-toggle sidebarCollapse">--}}
{{--                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">

{{--          <li class="menu {{ (request()->is('/admin_panel ')) ? 'active' : '' }}">--}}
{{--                <a href="#dashboard" data-bs-toggle="collapse" aria-expanded="true" class="dropdown-toggle">--}}
{{--                    <div class="">--}}
{{--                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>--}}
{{--                        <span>لوحة التحكم</span>--}}
{{--                    </div>--}}
{{--                    <div>--}}
{{--                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--                <ul class="collapse submenu list-unstyled show" id="dashboard" data-bs-parent="#accordionExample">--}}
{{--                    <li class="{{ (request()->is('/admin_panel')) ? 'active' : '' }}">--}}
{{--                        <a href="/admin_panel"> المخططات </a>--}}
{{--                    </li>--}}
{{--                </ul>--}}
{{--            </li>--}}

            <li class="menu {{ (request()->is('*/editAbout*')) ? 'active' : '' }}">
                <a href="/admin_panel/editAbout" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-feather"><path d="M20.24 12.24a6 6 0 0 0-8.49-8.49L5 10.5V19h8.5z"></path><line x1="16" y1="8" x2="2" y2="22"></line><line x1="17.5" y1="15" x2="9" y2="15"></line></svg>
                        <span> نبذة عن</span>
                    </div>
                </a>
            </li>

            


            <li class="menu {{ (request()->is('*/editWe*')) ? 'active' : '' }}">
                <a href="/admin_panel/editWe" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-help-circle"><circle cx="12" cy="12" r="10"></circle><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>
                        <span> من نحن</span>
                    </div>
                </a>
            </li>

            
            <li class="menu {{ (request()->is('*/contact*')) ? 'active' : '' }}">
                <a href="/admin_panel/contact" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>تواصل معنا</span>
                    </div>
                </a>
            </li>  


            <li class="menu {{ (request()->is('*/yourProject*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.yourProject.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>
                        <span> خطوات المشروع </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/services*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.services.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trello"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><rect x="7" y="7" width="3" height="9"></rect><rect x="14" y="7" width="3" height="5"></rect></svg>
                        <span> خدماتنا  </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/blogs*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.blogs.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clipboard"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect></svg>
                        <span> المدونة  </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/works*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.works.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-briefcase"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>
                        <span> أعمالنا  </span>
                    </div>
                </a>
            </li>

            {{-- <li class="menu {{ (request()->is('*/counters*')) ? 'active' : '' }}">--}}
                {{--<a href="{{route('admin_panel.counters.index')}}" aria-expanded="false" class="dropdown-toggle">--}}
                       {{-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sliders"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>--}}
                        {{--<span> العدادات  </span>--}}
                    {{--</div>--}}
                {{--</a>--}}
           {{-- </li> --}}


           

           <li class="menu {{ (request()->is('*/meta*')) ? 'active' : '' }}">
                        <a href="#elements" data-bs-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <div class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-cpu"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>
                                <span>اعدادات SEO</span>
                            </div>
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                            </div>
                        </a>

                        
                        <ul class="collapse submenu list-unstyled" id="elements" data-bs-parent="#accordionExample">
                            <li>
                                <a href="{{route('admin_panel.meta.index')}}"> الصفحة الرئيسية </a>
                            </li>
                        </ul>
                        <ul class="collapse submenu list-unstyled" id="elements" data-bs-parent="#accordionExample">
                            <li>
                                <a href="{{route('admin_panel.bolg_meta.index')}}">  صفحة المدونة </a>
                            </li>
                        </ul>
            </li>


            <li class="menu {{ (request()->is('*/media*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.media.edit',1)}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tv"><rect x="2" y="7" width="20" height="15" rx="2" ry="2"></rect><polyline points="17 2 12 7 7 2"></polyline></svg>
                        <span>  التواصل الاجتماعي  </span>
                    </div>
                </a>
            </li>





        </ul>

    </nav>

</div>
<!--  END SIDEBAR  -->